# Generated by Django 3.2.15 on 2024-02-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0025_delete_submissioncounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='geom',
        ),
    ]
